---
# Kevin M. Meziere <kmeziere@jpcatholic.com>
# Copyright 2015, John Paul the Great Catholic University

leofs_release: rel
leofs_storage_version_required: leo_storage-1.2.16
leofs_cookie: <<leofs_cookie>>
leofs_master: <<leofs_master>>
leofs_slave: <<leofs_slave>>
fifo_gpg_keyid: BB975564
